using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BusinesEntities
{
    public partial class PasswordProtection
    {
        public int Id { get; set; }
        public string Password { get; set; }
        public DateTime ScheduleDate { get; set; }
        public DateTime ScheduleTime { get; set; }
        public string AutoGeneratedLink { get; set; }
        public int EventId { get; set; }

    }
}
